watch_stylesheet: true
watch_config: true
debug: true
komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop"
  reload_command: "komorebic stop && komorebic start --whkd"
bars:
  status-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: true
      round_corners: false
      border_color: None
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 25
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      left: ["clock", "komorebi_workspaces", "quick_launch"]
      center: ["media", "cava"]
      right: ["wifi", "wallpapers", "weather", "volume"]
widgets:
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%H:%M:%S}  |"
      timezones: []
      callbacks:
        on_left: "do_nothing"
        on_right: "do_nothing"
  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      label_offline: "天 offline"
      label_workspace_btn: "{index}"
      label_workspace_active_btn: "{index}"
      label_workspace_populated_btn: "{index}"
      hide_empty_workspaces: true
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "vol {level}"
      callbacks:
        on_right: "toggle_mute"
        on_left: "do_nothing"
  media:
    type: yasb.media.MediaWidget
    options:
      label: '{title}{s}{artist}'
      label_alt: '{title}'
      separator: ' - '
      hide_empty: true
      callbacks:
        on_left: toggle_media_menu
        on_middle: do_nothing
        on_right: do_nothing
      max_field_size:
        label: 45
        label_alt: 45
      show_thumbnail: false
      controls_only: false
      controls_left: true
      controls_hide: true
      thumbnail_alpha: 100
      thumbnail_padding: 10
      thumbnail_edge_fade: true
      icons:
        prev_track: "\uE892"
        next_track: "\uE893"
        play: "\uE768"
        pause: "\uE769"
      media_menu:
        blur: true
        round_corners: true
        round_corners_type: normal
        border_color: system
        alignment: center
        direction: down
        thumbnail_corner_radius: 20
        thumbnail_size: 100
        max_title_size: 100
        max_artist_size: 80
        show_volume_slider: false
  wallpapers:
    type: yasb.wallpapers.WallpapersWidget
    options:
      label: "<span> \uf4e5 </span>"
      tooltip: true
      image_path: "C:\\Users\\DELL\\.config\\Wallpapers"
      change_automatically: false
      engine:
        enabled: true
        animation: circle
      gallery:
        enabled: true
        blur: true
        image_width: 200
        image_per_page: 7
        gallery_columns: 0 
        horizontal_position: center
        vertical_position: center
        respect_work_area: true
        show_buttons: false
        orientation: portrait
        image_spacing: 6
        lazy_load: true
        lazy_load_fadein: 300
        image_corner_radius: 5
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span> {icon} </span> {temp}"
      label_alt: "<span> {icon} </span> {location}: Min {min_temp}, Max {max_temp}, Humidity {humidity}"
      api_key: 'f59a8bfa9e6f411e9bf150801260307'
      update_interval: 600 #Update interval in seconds, Min 600
      hide_decimal: true
      location: "Pacifica, ARG" #Los Angeles, CA, USA
      callbacks:
        on_left: "toggle_label"
      icons:
        sunnyDay: "\udb81\udd9a"
        clearNight: "\udb81\udd94"
        cloudyDay: "\udb81\udd90"
        cloudyNight: "\udb81\udd90"
        rainyDay: "\udb81\udd96"
        rainyNight: "\udb81\udd96"
        snowyDay: "\udb81\udd98"
        snowyNight: "\udb81\udd98"
        blizzardDay: "\udb83\udf36"
        default: "\udb81\udd90"
  quick_launch:
    type: "yasb.quick_launch.QuickLaunchWidget"
    options:
      label: "<span></span>"
      search_placeholder: "Search applications..."
      max_results: 30
      show_icons: true
      icon_size: 20
      popup:
        width: 650
        height: 400
        blur: false
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        dark_mode: true
      callbacks:
        on_left: "toggle_quick_launch"
      keybindings:
        - keys: "alt+space"
          action: "toggle_quick_launch"
          screen: "primary"
  wifi:
    type: yasb.wifi.WifiWidget
    options:
      label: "<span>{wifi_icon}</span>"
      label_alt: "<span>{wifi_icon}</span>{wifi_name}"
      update_interval: 1000
      wifi_icons:
        - ""
        - ""
        - ""
        - ""
        - ""
  cava:
    type: "yasb.cava.CavaWidget"
    options:
      bar_height: 6
      min_bar_height: 0
      gradient: 1
      foreground: "#000000"
      gradient_color_1: '#ffffff'
      gradient_color_2: '#ffffff'
      gradient_color_3: '#ffffff'
      bars_number: 6
      bar_spacing: 1
      bar_width: 3
      bar_type: "bars"
      framerate: 60
      hide_empty: true
